name: Check API Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: 获取API数据并更新JSON
        run: |
          current_time=$(date -Is)
          month_ago=$(date -Is -d "1 month ago")
          
          # 获取API数据并验证
          response=$(curl -s "https://blogapi.pysio.online/check")
          
          # 打印响应以进行调试
          echo "API Response:"
          echo "$response"
          
          # 验证响应是否为有效的JSON并进行预处理
          if ! response_json=$(echo "$response" | jq -R -s -c '.' | jq '.'); then
            echo "Error: Invalid JSON response"
            exit 1
          fi
          
          # 检查JSON文件是否存在
          if [ ! -f "cheak.json" ]; then
            echo "[]" > cheak.json
          fi
          
          # 读取现有数据
          existing_data=$(cat cheak.json)
          
          # 处理新数据（添加错误处理）
          new_entry=$response_json
          new_entry_compare=$(echo "$new_entry" | jq 'del(.last_heartbeat)')
          
          # 检查是否存在记录
          if [ "$(echo "$existing_data" | jq 'length')" -eq 0; then
            # 第一条记录
            updated_data=$(echo "[]" | jq --arg time "$current_time" --argjson data "$new_entry" \
              '. + [{start_time: $time, end_time: null, data: $data}]')
          else
            last_entry=$(echo "$existing_data" | jq -r 'last')
            last_entry_compare=$(echo "$last_entry.data" | jq 'del(.last_heartbeat)')
            
            if jq -n --argjson a "$last_entry_compare" --argjson b "$new_entry_compare" '$a == $b'; then
              # 数据相同，更新最后一条记录的 end_time
              updated_data=$(echo "$existing_data" | jq --arg time "$current_time" \
                '[.[0:-1], (.[-1] | .end_time = $time)] | flatten')
            else
              # 数据有变化，添加新记录
              updated_data=$(echo "$existing_data" | jq --arg time "$current_time" --argjson data "$new_entry" \
                '[.[0:-1], (.[-1] | .end_time = $time), {start_time: $time, end_time: null, data: $data}] | flatten')
            fi
          fi
          
          # 写入文件（添加错误处理）
          if ! echo "$updated_data" | jq . > cheak.json; then
            echo "Error: Failed to write JSON file"
            exit 1
          fi

      - name: 配置 Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: 提交更改
        run: |
          git add cheak.json
          if git diff --cached --quiet; then
            echo "没有检测到更改，跳过提交。"
          else
            git commit -m "自动更新 API 检查数据"
            git push origin HEAD:${{ github.ref }}