name: Download and Commit Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: 下载并重命名文件
        run: |
          if [ -f ".github/link.json" ]; then
            jq -c '.[]' .github/link.json | while read -r item; do
              filename=$(echo "$item" | jq -r '.filename')
              link=$(echo "$item" | jq -r '.link')
              curl -L -o "$filename" "$link"
            done
          else
            echo "link.json 文件不存在"
            exit 1
          fi

      - name: 配置 Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: 提交更改
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "没有检测到更改，跳过提交。"
          else
            git commit -m "自动下载并更新文件"
            git push origin HEAD:${{ github.ref }}
          fi