name: Download and Commit Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Adjust this cron expression to your timezone

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Read and Process JSON
        id: process-json
        run: |
          if [ -f ".github/link.json" ]; then
            while IFS= read -r line; do
              filename=$(echo "$line" | jq -r '.filename')
              link=$(echo "$line" | jq -r '.link')
              curl -s -f "$link" -o "$filename" || echo "Failed to download $link to $filename"
            done < <(jq -c '.[]' .github/link.json)
          else
            echo "::error file=.github/link.json::link.json file not found"
          fi

      - name: Add files
        run: git add *

      - name: Commit changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Download files from link.json" || echo "Git commit failed"
          fi

      - name: Push changes
        if: success()
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}