name: Download and Commit Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Adjust this cron expression to your timezone

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Read JSON file
        id: read-json
        run: |
          if [ -f ".github/link.json" ]; then
            echo "::set-output name=json_data::$(cat .github/link.json)"
          else
            echo "::error file=.github/link.json::link.json file not found"
          fi

      - name: Download and rename files
        run: |
          if [ -n "${{ steps.read-json.outputs.json_data }}" ]; then
            jq -r '.[] | "\(.filename) \(.link)"' <<< "${{ steps.read-json.outputs.json_data }}" | while IFS=' ' read -r filename link; do
              curl -s -f "$link" -o "$filename" || echo "Failed to download $link to $filename"
            done
          fi

      - name: Add files
        run: git add *

      - name: Commit changes
        run: if git diff-index --quiet HEAD --; then echo "No changes to commit"; else git commit -m "Download files from link.json"; fi

      - name: Push changes
        if: success()
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}